<?php
$courses = [
    [
        "id" => 1,
        "title" => "React Avançado",
        "platform" => "Udemy",
        "platformIcon" => "/udemy.svg",
        "tag" => "Frontend",
        "thumbnail" => "/react-course.jpg",
        "progress" => 80,
    ],
    [
        "id" => 2,
        "title" => "UX Design Essencial",
        "platform" => "Alura",
        "platformIcon" => "/alura.svg",
        "tag" => "UX",
        "thumbnail" => "/ux-course.jpg",
        "progress" => 45,
    ],
    [
        "id" => 3,
        "title" => "Inglês para Programadores",
        "platform" => "YouTube",
        "platformIcon" => "/youtube.svg",
        "tag" => "Inglês",
        "thumbnail" => "/english-course.jpg",
        "progress" => 60,
    ],
    [
        "id" => 4,
        "title" => "Node.js Completo",
        "platform" => "Udemy",
        "platformIcon" => "/udemy.svg",
        "tag" => "Backend",
        "thumbnail" => "/node-course.jpg",
        "progress" => 30,
    ],
    [
        "id" => 5,
        "title" => "Figma do Zero",
        "platform" => "Alura",
        "platformIcon" => "/alura.svg",
        "tag" => "Design",
        "thumbnail" => "/figma-course.jpg",
        "progress" => 90,
    ],
    [
        "id" => 6,
        "title" => "TypeScript Masterclass",
        "platform" => "Udemy",
        "platformIcon" => "/udemy.svg",
        "tag" => "Frontend",
        "thumbnail" => "/ts-course.jpg",
        "progress" => 10,
    ],
    [
        "id" => 7,
        "title" => "Banco de Dados SQL",
        "platform" => "Alura",
        "platformIcon" => "/alura.svg",
        "tag" => "Banco de Dados",
        "thumbnail" => "/sql-course.jpg",
        "progress" => 55,
    ],
    [
        "id" => 8,
        "title" => "Docker para Iniciantes",
        "platform" => "YouTube",
        "platformIcon" => "/youtube.svg",
        "tag" => "DevOps",
        "thumbnail" => "/docker-course.jpg",
        "progress" => 20,
    ],
];
